language: php

php:
- '7.2'

services:
- mysql

before_install:
- chmod +x bin/console
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
- composer install

script:
- bin/console doctrine:schema:drop
- bin/console doctrine:schema:create
-  SYMFONY_DEPRECATIONS_HELPER='/Doctrine\\Common\\ClassLoader is deprecated\./' ./vendor/bin/simple-phpunit
